#!/bin/sh

source fzf-git.sh

cbr() {
	git branch | grep '*' | cut -c 3- | xargs echo -n
}

br() {
	_fzf_git_branches
}

brr() {
	git branch -a --format='%(refname:short)' | grep origin | fzf
}

cmt() {
	_fzf_git_hashes
}

fls() {
	_fzf_git_files
}

stf () {
	git s | grep '^[MA]' | cut -c 4- | fzf -m
}

ustf() {
	git s | grep '^ M' | cut -c 4- | fzf -m
}

uustf() {
	git s | grep -E '^(\?\?| [MD])' | fzf -m | cut -c 4-
}



