#!/bin/sh

br() {
	git branch --format='%(refname:short)' | fzf
}

brr() {
	git branch -a --format='%(refname:short)' | grep origin | fzf
}

cmt() {
	git log --format='%C(bold yellow)%h%C(reset) %s' -n 10 | fzf | cut -f 1 -d " "	
}

stf () {
	git s | grep '^[MA]' | cut -c 4- | fzf -m
}

ustf() {
	git s | grep '^ M' | cut -c 4- | fzf -m
}

uustf() {
	git s | grep -E '^(\?\?| [MD])' | fzf -m | cut -c 4-
}



