
[font]
size = 16

[terminal]
shell = "/opt/homebrew/bin/fish"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Maximized"
option_as_alt = "Both"

[window.dimensions]
columns = 130
lines = 50

[colors]
draw_bold_text_with_bright_colors = true

[env]
  TERM = "xterm-256color"

[[hints.enabled]]
regex = "[a-zA-Z0-9]{10} "
action = "Paste"
post_processing = true
binding = { key = "C", mods = "Alt|Shift" }

[[hints.enabled]]
regex = '[^ ]*/[[[:alnum:]]._-]+'
action = "Paste"
binding = { key = "F", mods = "Alt|Shift" }

