theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
end-of-line-diagnostics = "warning"

[editor.cursor-shape]
insert = "bar"

[keys.normal.C-f]
f = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/open_file.sh %f"
h = ":sh echo %f"
